-quiet
-splash
-plymouth.ignore-serial-consoles
-plymouth.prefer-fbcon
clk_ignore_unused
iommu.passthrough=0
arm-smmu.disable_bypass=0
console=tty0
no_console_suspend
printk.devkmsg=on
loglevel=4
fbcon=map:0
fbcon=font:TER16x32
fbcon=vc:1-1
printk.time=1
panic=0
oops=panic
consoleblank=0
