#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
	cat <<'USAGE'
Usage: wrap-pmaports-boot-avb.sh --boot-image FILE --outdir DIR [options]

Validate a postmarketOS Android boot image for the OnePlus 7T Pro and create a
partition-sized AVB copy suitable for a guarded persistent-write transaction.
The input image is never modified.

Options:
  --boot-image FILE     Raw header-v2 boot.img generated by boot-deploy.
  --outdir DIR          New output directory. It must not already exist.
  --partition-size N    Boot partition size in bytes (default: 100663296).
  -h, --help            Show this help.
USAGE
}

die() {
	printf '[pmaports-avb] ERROR: %s\n' "$*" >&2
	exit 1
}

note() {
	printf '[pmaports-avb] %s\n' "$*"
}

require_command() {
	command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

cmdline_has_token() {
	local cmdline="$1"
	local token="$2"

	[[ " $cmdline " == *" $token "* ]]
}

boot_image=""
outdir=""
partition_size=100663296

while [ "$#" -gt 0 ]; do
	case "$1" in
		--boot-image)
			[ "$#" -ge 2 ] || die "--boot-image requires a value"
			boot_image="$2"
			shift
			;;
		--outdir)
			[ "$#" -ge 2 ] || die "--outdir requires a value"
			outdir="$2"
			shift
			;;
		--partition-size)
			[ "$#" -ge 2 ] || die "--partition-size requires a value"
			partition_size="$2"
			shift
			;;
		-h|--help)
			usage
			exit 0
			;;
		*)
			usage >&2
			die "unknown argument: $1"
			;;
	esac
	shift
done

[ -n "$boot_image" ] || die "--boot-image is required"
[ -n "$outdir" ] || die "--outdir is required"
[[ "$partition_size" =~ ^[0-9]+$ ]] || die "partition size must be a positive integer"
[ "$partition_size" -gt 0 ] || die "partition size must be greater than zero"

for command_name in avbtool cmp cp grep mkdir realpath sed sha256sum stat unpack_bootimg wc; do
	require_command "$command_name"
done

boot_image="$(realpath -- "$boot_image")"
outdir="$(realpath -m -- "$outdir")"
[ -f "$boot_image" ] || die "boot image not found: $boot_image"
[ -s "$boot_image" ] || die "boot image is empty: $boot_image"
[ ! -e "$outdir" ] || die "output path already exists: $outdir"

mkdir -p "$outdir/components"
raw_image="$outdir/raw-boot.img"
avb_image="$outdir/boot.img"
report="$outdir/unpack.txt"

cp --reflink=auto "$boot_image" "$raw_image"
unpack_bootimg --boot_img "$raw_image" --out "$outdir/components" > "$report"

grep -qx 'boot magic: ANDROID!' "$report" || die "missing Android boot magic"
grep -qx 'boot image header version: 2' "$report" || die "boot image is not header version 2"
grep -qx 'page size: 4096' "$report" || die "unexpected boot-image page size"
grep -qx 'kernel load address: 0x00008000' "$report" || die "unexpected kernel load address"
grep -qx 'ramdisk load address: 0x01000000' "$report" || die "unexpected ramdisk load address"
grep -qx 'kernel tags load address: 0x00000100' "$report" || die "unexpected tags load address"
grep -qx 'dtb address: 0x0000000001f00000' "$report" || die "unexpected DTB load address"
grep -qx 'additional command line args: ' "$report" || die "header-v2 extra_cmdline must be empty"

cmdline="$(sed -n 's/^command line args: //p' "$report")"
[ -n "$cmdline" ] || die "kernel command line is empty"
cmdline_size="$(printf '%s' "$cmdline" | wc -c | tr -d ' ')"
[ "$cmdline_size" -le 511 ] || die \
	"kernel command line is $cmdline_size bytes; the tested HD1913 ABL forwards at most 511"

required_tokens=(
	"clk_ignore_unused"
	"iommu.passthrough=0"
	"arm-smmu.disable_bypass=0"
	"console=ttyGS0,115200"
	"console=tty0"
	"keep_bootcon"
	"loglevel=8"
	"ignore_loglevel"
	"fbcon=font:TER16x32"
	"panic=0"
	"oops=panic"
	"pmos_rootfsopts=defaults"
)
for token in "${required_tokens[@]}"; do
	cmdline_has_token "$cmdline" "$token" || die "missing required command-line token: $token"
done

for token in quiet splash plymouth.ignore-serial-consoles plymouth.prefer-fbcon; do
	cmdline_has_token "$cmdline" "$token" && die "forbidden command-line token: $token"
done

[[ "$cmdline" =~ (^|[[:space:]])pmos_boot_uuid=[0-9a-f-]{36}($|[[:space:]]) ]] ||
	die "missing or malformed pmos_boot_uuid"
[[ "$cmdline" =~ (^|[[:space:]])pmos_root_uuid=[0-9a-f-]{36}($|[[:space:]]) ]] ||
	die "missing or malformed pmos_root_uuid"

raw_size="$(stat -c '%s' "$raw_image")"
[ "$raw_size" -lt "$partition_size" ] || die \
	"raw image ($raw_size bytes) does not fit the $partition_size-byte boot partition"
raw_sha="$(sha256sum "$raw_image")"
raw_sha="${raw_sha%% *}"

note "adding deterministic AVB hash footer"
cp --reflink=auto "$raw_image" "$avb_image"
avbtool add_hash_footer \
	--image "$avb_image" \
	--partition_name boot \
	--partition_size "$partition_size" \
	--algorithm NONE \
	--salt "$raw_sha"

[ "$(stat -c '%s' "$avb_image")" -eq "$partition_size" ] ||
	die "AVB image does not match the requested partition size"
cmp -n "$raw_size" "$raw_image" "$avb_image" ||
	die "AVB footer generation changed the raw boot-image prefix"

avbtool info_image --image "$avb_image" > "$outdir/avb-info.txt"
avbtool verify_image --image "$avb_image" > "$outdir/avb-verify.txt"
grep -Eq 'Partition Name:[[:space:]]+boot$' "$outdir/avb-info.txt" ||
	die "AVB descriptor does not target the boot partition"
grep -q 'Algorithm:.*NONE' "$outdir/avb-info.txt" ||
	die "unexpected AVB algorithm"

sha256sum \
	"$raw_image" \
	"$avb_image" \
	"$outdir/components/kernel" \
	"$outdir/components/ramdisk" \
	"$outdir/components/dtb" \
	> "$outdir/SHA256SUMS"

avb_sha="$(sha256sum "$avb_image")"
avb_sha="${avb_sha%% *}"
cat > "$outdir/README.md" <<EOF
# OnePlus 7T Pro pmaports AVB candidate

- Raw boot image: \`$raw_sha\`
- Raw size: \`$raw_size\` bytes
- AVB boot image: \`$avb_sha\`
- AVB size: \`$partition_size\` bytes
- Command-line bytes: \`$cmdline_size\`
- AVB partition: \`boot\`
- AVB algorithm: \`NONE\`

The input header and extracted payloads passed the hotdog direct-boot contract.
This record is local build evidence, not proof of a hardware boot.
EOF

note "raw boot SHA256: $raw_sha"
note "AVB boot SHA256: $avb_sha"
note "command line: $cmdline_size bytes"
note "output: $outdir"
